namespace MultiFunPlayer.Input;

public interface IInputGestureDescriptor;
public interface ISimpleInputGestureDescriptor : IInputGestureDescriptor;
public interface IAxisInputGestureDescriptor : IInputGestureDescriptor;