namespace MultiFunPlayer.Input;

internal interface IInputGestureDescriptor;
internal interface ISimpleInputGestureDescriptor : IInputGestureDescriptor;
internal interface IAxisInputGestureDescriptor : IInputGestureDescriptor;